#!/usr/bin/sh

if [[ -z "${DESTDIR}" ]]; then
DESTDIR="/"
fi

EXE=$DESTDIR/usr/local/bin/socks5-proxy
UI=$DESTDIR/usr/local/bin/socks5-interface
ICON=$DESTDIR/usr/local/share/icons/socks5-interface.png
DESKTOP=$DESTDIR/usr/local/share/applications/socks5-interface.desktop
CONFIG=$DESTDIR/etc/socks5-config.txt
SERVICE=$DESTDIR/usr/lib/systemd/system/socks5-proxy.service
DATABASE=$DESTDIR/tmp/sessions_stat.db

if [ "$1" != "-r" ]
then
    mkdir -p $DESTDIR/usr/local/share/icons
    cp -f installer/socks5-interface.desktop $DESKTOP
    cp -f installer/socks5-interface.png $ICON
    cp -f service/linux/socks5-proxy.service $SERVICE
    cp -f build/bin/main $EXE
    cp -f build/bin/interface $UI
    cp -f config.txt $CONFIG
    touch $DATABASE
    chmod 666 $DATABASE
    chmod +x $SERVICE
    chmod +x $EXE
    chmod +x $UI
    chmod 666 $DATABASE
    systemctl daemon-reload
else
    rm -f $ICON
    rm -f $DESKTOP
    rm -f $SERVICE
    rm -f $EXE
    rm -f $UI
    rm -f $CONFIG
    rm -f $DATABASE
    systemctl daemon-reload
fi
