#!/usr/bin/sh
if [ "$1" != "-r" ]
then
    cp -bf service/linux/socks5-proxy.service /usr/lib/systemd/system
    cp -bf bin/main /usr/local/bin/service
    cp -bf config.txt /etc/socks5-config.txt
    chmod +x /usr/lib/systemd/system/socks5-proxy.service
    chmod +x /usr/local/bin/service
    systemctl daemon-reload
else
    rm -f /usr/lib/systemd/system/socks5-proxy.service
    rm -f /usr/local/bin/service
    rm -f /etc/socks5-config.txt
    systemctl daemon-reload
fi