# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/derpy/git/socks5-proxy-SUM-2022

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/derpy/git/socks5-proxy-SUM-2022

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/derpy/git/socks5-proxy-SUM-2022/CMakeFiles /home/derpy/git/socks5-proxy-SUM-2022//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/derpy/git/socks5-proxy-SUM-2022/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LogConfigReader

# Build rule for target.
LogConfigReader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LogConfigReader
.PHONY : LogConfigReader

# fast build rule for target.
LogConfigReader/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LogConfigReader.dir/build.make CMakeFiles/LogConfigReader.dir/build
.PHONY : LogConfigReader/fast

#=============================================================================
# Target rules for targets named Logger

# Build rule for target.
Logger: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Logger
.PHONY : Logger

# fast build rule for target.
Logger/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Logger.dir/build.make CMakeFiles/Logger.dir/build
.PHONY : Logger/fast

#=============================================================================
# Target rules for targets named proxy_test

# Build rule for target.
proxy_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 proxy_test
.PHONY : proxy_test

# fast build rule for target.
proxy_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proxy_test.dir/build.make CMakeFiles/proxy_test.dir/build
.PHONY : proxy_test/fast

#=============================================================================
# Target rules for targets named tcp_connection

# Build rule for target.
tcp_connection: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tcp_connection
.PHONY : tcp_connection

# fast build rule for target.
tcp_connection/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_connection.dir/build.make CMakeFiles/tcp_connection.dir/build
.PHONY : tcp_connection/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

src/LogConfigReader.o: src/LogConfigReader.cpp.o
.PHONY : src/LogConfigReader.o

# target to build an object file
src/LogConfigReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LogConfigReader.dir/build.make CMakeFiles/LogConfigReader.dir/src/LogConfigReader.cpp.o
.PHONY : src/LogConfigReader.cpp.o

src/LogConfigReader.i: src/LogConfigReader.cpp.i
.PHONY : src/LogConfigReader.i

# target to preprocess a source file
src/LogConfigReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LogConfigReader.dir/build.make CMakeFiles/LogConfigReader.dir/src/LogConfigReader.cpp.i
.PHONY : src/LogConfigReader.cpp.i

src/LogConfigReader.s: src/LogConfigReader.cpp.s
.PHONY : src/LogConfigReader.s

# target to generate assembly for a file
src/LogConfigReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LogConfigReader.dir/build.make CMakeFiles/LogConfigReader.dir/src/LogConfigReader.cpp.s
.PHONY : src/LogConfigReader.cpp.s

src/Logger.o: src/Logger.cpp.o
.PHONY : src/Logger.o

# target to build an object file
src/Logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Logger.dir/build.make CMakeFiles/Logger.dir/src/Logger.cpp.o
.PHONY : src/Logger.cpp.o

src/Logger.i: src/Logger.cpp.i
.PHONY : src/Logger.i

# target to preprocess a source file
src/Logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Logger.dir/build.make CMakeFiles/Logger.dir/src/Logger.cpp.i
.PHONY : src/Logger.cpp.i

src/Logger.s: src/Logger.cpp.s
.PHONY : src/Logger.s

# target to generate assembly for a file
src/Logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Logger.dir/build.make CMakeFiles/Logger.dir/src/Logger.cpp.s
.PHONY : src/Logger.cpp.s

src/proxy_test.o: src/proxy_test.cpp.o
.PHONY : src/proxy_test.o

# target to build an object file
src/proxy_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proxy_test.dir/build.make CMakeFiles/proxy_test.dir/src/proxy_test.cpp.o
.PHONY : src/proxy_test.cpp.o

src/proxy_test.i: src/proxy_test.cpp.i
.PHONY : src/proxy_test.i

# target to preprocess a source file
src/proxy_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proxy_test.dir/build.make CMakeFiles/proxy_test.dir/src/proxy_test.cpp.i
.PHONY : src/proxy_test.cpp.i

src/proxy_test.s: src/proxy_test.cpp.s
.PHONY : src/proxy_test.s

# target to generate assembly for a file
src/proxy_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/proxy_test.dir/build.make CMakeFiles/proxy_test.dir/src/proxy_test.cpp.s
.PHONY : src/proxy_test.cpp.s

src/server.o: src/server.cpp.o
.PHONY : src/server.o

# target to build an object file
src/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server.cpp.o
.PHONY : src/server.cpp.o

src/server.i: src/server.cpp.i
.PHONY : src/server.i

# target to preprocess a source file
src/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server.cpp.i
.PHONY : src/server.cpp.i

src/server.s: src/server.cpp.s
.PHONY : src/server.s

# target to generate assembly for a file
src/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server.cpp.s
.PHONY : src/server.cpp.s

src/tcp_connection.o: src/tcp_connection.cpp.o
.PHONY : src/tcp_connection.o

# target to build an object file
src/tcp_connection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_connection.dir/build.make CMakeFiles/tcp_connection.dir/src/tcp_connection.cpp.o
.PHONY : src/tcp_connection.cpp.o

src/tcp_connection.i: src/tcp_connection.cpp.i
.PHONY : src/tcp_connection.i

# target to preprocess a source file
src/tcp_connection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_connection.dir/build.make CMakeFiles/tcp_connection.dir/src/tcp_connection.cpp.i
.PHONY : src/tcp_connection.cpp.i

src/tcp_connection.s: src/tcp_connection.cpp.s
.PHONY : src/tcp_connection.s

# target to generate assembly for a file
src/tcp_connection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_connection.dir/build.make CMakeFiles/tcp_connection.dir/src/tcp_connection.cpp.s
.PHONY : src/tcp_connection.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... LogConfigReader"
	@echo "... Logger"
	@echo "... proxy_test"
	@echo "... server"
	@echo "... tcp_connection"
	@echo "... src/LogConfigReader.o"
	@echo "... src/LogConfigReader.i"
	@echo "... src/LogConfigReader.s"
	@echo "... src/Logger.o"
	@echo "... src/Logger.i"
	@echo "... src/Logger.s"
	@echo "... src/proxy_test.o"
	@echo "... src/proxy_test.i"
	@echo "... src/proxy_test.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
	@echo "... src/tcp_connection.o"
	@echo "... src/tcp_connection.i"
	@echo "... src/tcp_connection.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

