#!/usr/bin/sh
if [$1 == "-r"]
then
    cp socks5-proxy.service /usr/lib/systemd/system
    systemctl daemon-reload
else
    rm -f /usr/lib/systemd/system/socks5-proxy.service
    systemctl daemon-reload
fi

